# Generated by Django 3.2.5 on 2021-08-21 18:41

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210818_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_poster',
            field=models.ImageField(blank=True, null=True, upload_to='course_posters', verbose_name='Upload a course poster'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quiz_url',
            field=models.URLField(blank=True, verbose_name='Quiz link'),
        ),
    ]
