# Generated by Django 3.2.5 on 2021-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210822_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_poster',
            field=models.ImageField(blank=True, null=True, upload_to='course_posters', verbose_name='Upload a course poster'),
        ),
    ]
