# Generated by Django 3.2.5 on 2021-08-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegister',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('image', models.ImageField(null=True, upload_to='course_posters', verbose_name='Upload a course poster')),
            ],
        ),
    ]
