# Generated by Django 3.2.5 on 2021-08-30 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregister',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacherregister',
            name='image',
            field=models.ImageField(null=True, upload_to='course_posters', verbose_name='Upload teacher id card image'),
        ),
    ]
