# Generated by Django 3.2.5 on 2021-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210830_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherregister',
            name='image',
        ),
        migrations.AddField(
            model_name='teacherregister',
            name='institute',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
