# Generated by Django 3.2.5 on 2021-09-06 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='id',
        ),
        migrations.AddField(
            model_name='contactus',
            name='msg_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
