# Generated by Django 3.2.5 on 2021-09-06 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210906_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='msg_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
