# Generated by Django 3.2.5 on 2021-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210906_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='msg_id',
        ),
        migrations.AddField(
            model_name='contactus',
            name='update_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
