# Generated by Django 3.2.5 on 2021-09-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_update_id_contactus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='id',
            new_name='cno',
        ),
    ]
