# Generated by Django 3.2.5 on 2021-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_id_contactus_cno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='cno',
        ),
        migrations.AddField(
            model_name='contactus',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
