# Generated by Django 3.2.5 on 2021-09-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2zStore', '0004_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
