# Generated by Django 3.2.5 on 2021-09-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2zStore', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
